services:
  app:
    build:
      dockerfile: Dockerfile
      working_dir: /app
    volumes:
      - ./:/app
  awsdeployment:
    image: codeship/aws-deployment
    encrypted_env_file: env.encrypted
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes:
      - ./:/app
