services:
  app:
    build:
      image: app
      dockerfile: Dockerfile
    volumes_from:
      - data
  awsdeployment:
    image: codeship/aws-deployment
    encrypted_env_file: env.encrypted
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes_from:
      - data
  data:
    image: busybox
    volumes:
      - .:/app